environment:
  matrix:
    - nodejs_version: "10"
    - nodejs_version: "11"

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn

test_script:
  - node --version
  - yarn --version
  - yarn test

cache:
 - node_modules
 - "%LOCALAPPDATA%/Yarn"

# Don't actually build.
build: off
